# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Storybase API

on:
  push:
    branches:
      - master
    paths:
      - "StorybaseApi/**"  # Runs only if API files change
  workflow_dispatch:
    inputs:
      forceDeploy:
        description: "Force deploy API"
        required: false
        type: boolean

jobs:
  build:
    if: contains(github.event.head_commit.message, '[deploy-api]') || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build StorybaseApi/StorybaseApi.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish StorybaseApi/StorybaseApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    if: contains(github.event.head_commit.message, '[deploy-api]') || github.event_name == 'workflow_dispatch' || github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C285B3F5BA29453D8165ED511F441343 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_04B7580E5206465E80AF4A8BEF1A967A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE5D954880AF4CB5B27F0B749FF162A5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'storybase'
          slot-name: 'Production'
          package: .
          
